version: 2
jobs:
  npm-install:
    working_directory: ~/website
    docker:
      - image: circleci/node:8.0
    steps:
      - run:
         name: "Checking Versions"
         command: |
           node --version
           npm --version
      - checkout
      - restore_cache:
          keys:
            - node-8-cache-{{ arch }}-{{ .Branch }}-npm-{{ checksum "package-lock.json" }}
            - node-8-cache-{{ arch }}-{{ .Branch }}-npm-{{ checksum "package.json" }}
      - run:
          name: Install npm packages
          command: npm install
      - save_cache:
          key: node-8-cache-{{ arch }}-{{ .Branch }}-npm-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules/
      - save_cache:
          key: node-8-cache-{{ arch }}-{{ .Branch }}-npm-{{ checksum "package.json" }}
          paths:
            - ./node_modules/
  test-job:
    working_directory: ~/website
    docker:
      - image: circleci/node:8.0
    steps:
      - run:
         name: "Checking Versions"
         command: |
           node --version
           npm --version
      - checkout
      - restore_cache:
          keys:
            - node-8-cache-{{ arch }}-{{ .Branch }}-npm-{{ checksum "package-lock.json" }}
            - node-8-cache-{{ arch }}-{{ .Branch }}-npm-{{ checksum "package.json" }}
      - run:
          name: npm-test
          command: npm test
  build-job:
      working_directory: ~/website
      docker:
        - image: circleci/node:8.0
      steps:
        - run:
           name: "Checking Versions"
           command: |
             node --version
             npm --version
        - checkout
        - restore_cache:
            keys:
              - node-8-cache-{{ arch }}-{{ .Branch }}-npm-{{ checksum "package-lock.json" }}
              - node-8-cache-{{ arch }}-{{ .Branch }}-npm-{{ checksum "package.json" }}
        - run:
            name: npm-build
            command: npm run build
        - save_cache:
            key: dist-cache-{{ arch }}-{{ .Branch }}-{{ checksum "checkfile" }}
            paths:
              - ./dist/
  deploy:
      docker:
        - image: circleci/node:8.0
      working_directory: ~/website
      steps:
        - run:
            name: "Checking Versions"
            command: |
              node --version
              npm --version
        - checkout
        - restore_cache:
            keys:
              - node-8-cache-{{ arch }}-{{ .Branch }}-npm-{{ checksum "package.json" }}
        - restore_cache:
            keys:
              - dist-cache-{{ arch }}-{{ .Branch }}-
        - run:
            name: Use Prod
            command: ./node_modules/.bin/firebase use prod --token=$FIREBASE_DEPLOY_TOKEN
        - run:
            name: Deploy to Firebase
            command: ./node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2

  build-and-deploy:
    jobs:
      - npm-install
      - test-job:
          requires:
            - npm-install
      - build-job:
          requires:
            - test-job
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-job
          filters:
            branches:
              only: master